### ISSUE TITLE
Installing issue - im newbie

### ISSUE THREAD

**Issue by Simonk007** [Singosgu/GreaterWMS#8]
## Hi,
im trying to install this nice tool on my ubuntu 20 server but im kinda stock.
i have followed install guide

## Makemigrations the Database:
python manage.py makemigrations
### getting this error:   
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax

### Hope you can help getting it running

**Comment by Singosgu** [comment]
Hi Simonk:

1. You should confirm your ubuntu has python version 3.8+
2. If you run it in Linux, such as ubuntu debian centos , you must use 
python3 manage.py makemigrations
not
python manage.py makemigrations

**Comment by Simonk007** [comment]
Thx for you fast help.

How do i change listen IP. As standard it is listening on 127.0.0.1 - im just testing so i want it listen to IP og server

Hope you can help me out

**Comment by Simonk007** [comment]
## Hi Again,
im managed to get server listen on server ip by running this command: daphne -p 8008 -b 192.168.254.19 greaterwms.asgi:application

Connecting to http://192.168.254.19:8008 - im getting this in my browser: Server Error (500)

### Console errors
``````
root@ubuntutest:/home/simon/greaterwms/GreaterWMS# daphne -p 8008 -b 192.168.254.19 greaterwms.asgi:application
Welcome To GreaterWMS
2021-01-10 19:44:13,521 INFO     Starting server at tcp:port=8008:interface=192.168.254.19
2021-01-10 19:44:13,521 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-01-10 19:44:13,521 INFO     Configuring endpoint tcp:port=8008:interface=192.168.254.19
2021-01-10 19:44:13,522 INFO     Listening on TCP address 192.168.254.19:8008
2021-01-10 19:45:04,959 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:49804 - - [10/Jan/2021:19:45:05] "GET /" 500 145
192.168.254.23:49804 - - [10/Jan/2021:19:45:05] "GET /favicon.ico" 200 7120
2021-01-10 19:45:49,611 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:49804 - - [10/Jan/2021:19:45:49] "GET /" 500 145
2021-01-10 19:46:35,481 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:49804 - - [10/Jan/2021:19:46:35] "GET /" 500 145
2021-01-10 19:46:46,059 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:49804 - - [10/Jan/2021:19:46:46] "GET /" 500 145
2021-01-10 19:47:24,341 INFO     Killed 0 pending application instances
``````

**Comment by Singosgu** [comment]
daphne -p 8008 -b 0.0.0.0 greaterwms.asgi:application
then you must edit axios_request.js 

## from
const baseurl = 'http://127.0.0.1:8008/'
const wsurl = 'ws://127.0.0.1:8008/'

## to
const baseurl = 'http://192.168.254.19:8008/'
const wsurl = 'ws://192.168.254.19:8008/'

final:
~~~shell
cd /{your file address}/templates
quasar build 
~~~



now, It can run well



otherwise:

yesterday I fix apidoc bug .  And till now it not the final release version

**Comment by Simonk007** [comment]
## Mornings,
So i did the as you wrote.

### Running the following command i got an error:
```console
root@ubuntutest:/home/simon/greaterwms/GreaterWMS/templates# quasar build
quasar: command not found
```
I managed to correct the quasar command not found. By installing NPM and quasar/cli
i used the following commands for that
```
sudo apt install npm
sudo npm i -g @quasar/cli
```
Then i tried doing quasar build command again in the /templates folder - result i get:
```
root@ubuntutest:/home/simon/greaterwms/GreaterWMS/templates# quasar build

 Error Unknown command "build"


  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|

  Running @quasar/cli v1.1.3

  Example usage
    $ quasar <command> <options>

  Help for a command
    $ quasar <command> --help
    $ quasar <command> -h

  Options
    --version, -v Print Quasar CLI version

  Commands
    create    Create a project folder
    info      Display info about your machine
                   (and your App if in a project folder)
    upgrade   Check (and optionally) upgrade Quasar packages
                   from a Quasar project folder
    serve     Create an ad-hoc server on App's distributables
    help, -h  Displays this message

  --------------
  => IMPORTANT !
  => Trigger this inside of a Quasar project (and npm/yarn install) for more commands.
  --------------
```
So what am i doing wrong?

**Comment by Singosgu** [comment]
it seems your quasar environmentis not correct.
you could try npm install
and if any other issue , npm will tell you what you must install for this project . 

I help you rebuild it already
https://github.com/Singosgu/ForSimon
you can clone it , then update the folder 'dist'.

**Comment by Simonk007** [comment]
## Hi again,
i copied all files and folders to root of Greaterwms.  
I ran the server again, but im still getting error

```
Welcome To GreaterWMS
2021-01-12 08:17:45,798 INFO     Starting server at tcp:port=8008:interface=0.0.0.0
2021-01-12 08:17:45,799 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-01-12 08:17:45,799 INFO     Configuring endpoint tcp:port=8008:interface=0.0.0.0
2021-01-12 08:17:45,799 INFO     Listening on TCP address 0.0.0.0:8008
2021-01-12 08:17:53,277 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:55736 - - [12/Jan/2021:08:17:53] "GET /" 500 145
192.168.254.23:55736 - - [12/Jan/2021:08:17:53] "GET /favicon.ico" 200 7120
2021-01-12 08:17:54,331 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:55736 - - [12/Jan/2021:08:17:54] "GET /" 500 145
192.168.254.23:55736 - - [12/Jan/2021:08:17:54] "GET /favicon.ico" 200 7120
```
## I also ran NPM install
```
root@ubuntutest:/home/simon/greaterwms/GreaterWMS# npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/simon/greaterwms/GreaterWMS/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/simon/greaterwms/GreaterWMS/package.json'
npm WARN GreaterWMS No description
npm WARN GreaterWMS No repository field.
npm WARN GreaterWMS No README data
npm WARN GreaterWMS No license field.
```

**Comment by Singosgu** [comment]
cd /home/simon/greaterwms/GreaterWMS/templates

**Comment by Simonk007** [comment]
hmm 
im confused :)

i copied the files into 
home/simon/greaterwms/GreaterWMS/templates/spa

also
home/simon/greaterwms/GreaterWMS/templates (all files in root templates folder)

still getting errors

Welcome To GreaterWMS
2021-01-12 08:36:14,188 INFO     Starting server at tcp:port=8008:interface=0.0.0.0
2021-01-12 08:36:14,188 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-01-12 08:36:14,188 INFO     Configuring endpoint tcp:port=8008:interface=0.0.0.0
2021-01-12 08:36:14,189 INFO     Listening on TCP address 0.0.0.0:8008
2021-01-12 08:36:27,943 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/spa/index.html
192.168.254.23:56317 - - [12/Jan/2021:08:36:27] "GET /" 500 145
2021-01-12 08:36:29,761 ERROR    Internal Server Error: /

**Comment by Singosgu** [comment]
not home/simon/greaterwms/GreaterWMS/templates/spa
is home/simon/greaterwms/GreaterWMS/templates/dist/spa
folder dist under templates

**Comment by Simonk007** [comment]
Wee is working.
U are so awesome. Thx alot

**Comment by Singosgu** [comment]
It's a pleasure
thie version is not final version . 
I will write operation process before Feb, and finish V2.0.0 Final as well.
